AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "cross account Pipeline for CAST"
Globals:
  Function:
    Timeout: 300

Parameters:
  Prefix:
    Description: project prefix
    Type: String
    Default: CAST-

Resources:
  PipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: NewPipelineTestRoleAuto
      AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"codepipeline.amazonaws.com"},"Action":"sts:AssumeRole"}]}'

  PipelineTempPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PipelineTemp
      Roles:
        - !Ref PipelineRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - codestar-connections:UseConnection
            Resource: arn:aws:codestar-connections:eu-west-1:214364534595:connection/8520c13f-d6df-4bfb-abd8-77605b5ac68d
            Effect: Allow

          - Action: # allos Git to load to S3 bucket
              - s3:*
            Resource: arn:aws:s3:::codepipeline-eu-west-1-*
            Effect: Allow

          - Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
            Resource: !Sub arn:aws:cloudformation:eu-west-1:214364534595:stack/${Prefix}*
            Effect: Allow

          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
            Resource:
              - arn:aws:codebuild:eu-west-1:214364534595:build/dpp-dco-cast-dev
              - arn:aws:codebuild:eu-west-1:214364534595:project/dpp-dco-cast-dev
              - arn:aws:codebuild:eu-west-1:214364534595:build/dpp-dco-cast-prod
              - arn:aws:codebuild:eu-west-1:214364534595:project/dpp-dco-cast-prod
              - arn:aws:codebuild:eu-west-1:214364534595:project/dpp-dco-cast-dev-ses

              - arn:aws:codebuild:eu-west-1:214364534595:project/dpp-dco-cast-* # shuld cover all use cases
              - arn:aws:codebuild:eu-west-1:214364534595:build/dpp-dco-cast-*

            Effect: Allow

          - Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
            Resource: "*"

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: codebuild-service-role-auto
      AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"codebuild.amazonaws.com"},"Action":"sts:AssumeRole"}]}'

  CodeBuildTempPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeBuildTemp
      Roles:
        - !Ref CodeBuildRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # allows to write logs
          - Effect: Allow
            Resource:
              - arn:aws:logs:eu-west-1:214364534595:log-group:*
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents

          - Effect: Allow
            Resource:
              - arn:aws:s3:::codepipeline-eu-west-1-*
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketAcl
              - s3:GetBucketLocation

          - Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::471685057907:role/CAST-DeployerRole-dev
              - arn:aws:iam::936022423514:role/CAST-DeployerRole-prod
            Effect: Allow

  CodeBuildMainDEV:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "dpp-dco-cast-dev"
      Source:
        BuildSpec: "deployment/buildspec/buildspec_dev.yaml"
        InsecureSsl: false
        Type: "CODEPIPELINE"
      Artifacts:
        EncryptionDisabled: false
        Name: "dpp-dco-cast-to-dev-auto"
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache: # consider using LOCAL SOURCE CACHE like here https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html
        Type: "NO_CACHE"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        EnvironmentVariables:
          - Name: "CODEBUILD_CONFIG_AUTO_DISCOVER"
            Type: "PLAINTEXT"
            Value: "true"
        Image: public.ecr.aws/amazonlinux/amazonlinux:2023
        ImagePullCredentialsType: "SERVICE_ROLE"
        PrivilegedMode: false
        Type: "LINUX_CONTAINER"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
        S3Logs:
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

  CodeBuildMainPROD:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "dpp-dco-cast-prod"
      Source:
        BuildSpec: "deployment/buildspec/buildspec_prod.yaml"
        InsecureSsl: false
        Type: "CODEPIPELINE"
      Artifacts:
        EncryptionDisabled: false
        Name: "dpp-dco-cast-to-prod-auto"
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache: # consider using LOCAL SOURCE CACHE like here https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html
        Type: "NO_CACHE"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        EnvironmentVariables:
          - Name: "CODEBUILD_CONFIG_AUTO_DISCOVER"
            Type: "PLAINTEXT"
            Value: "true"
        Image: public.ecr.aws/amazonlinux/amazonlinux:2023
        ImagePullCredentialsType: "SERVICE_ROLE"
        PrivilegedMode: false
        Type: "LINUX_CONTAINER"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
        S3Logs:
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

  CodeBuildSesDEV:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "dpp-dco-cast-dev-ses"
      Source:
        BuildSpec: "deployment/buildspec/buildspec_dev.yaml"
        InsecureSsl: false
        Type: "CODEPIPELINE"
      Artifacts:
        EncryptionDisabled: false
        Name: "dpp-dco-cast-to-dev-auto-ses"
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache: # consider using LOCAL SOURCE CACHE like here https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html
        Type: "NO_CACHE"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        EnvironmentVariables:
          - Name: "CODEBUILD_CONFIG_AUTO_DISCOVER"
            Type: "PLAINTEXT"
            Value: "true"
        Image: public.ecr.aws/amazonlinux/amazonlinux:2023
        ImagePullCredentialsType: "SERVICE_ROLE"
        PrivilegedMode: false
        Type: "LINUX_CONTAINER"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
        S3Logs:
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

  CodeBuildSesPROD:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "dpp-dco-cast-prod-ses"
      Source:
        BuildSpec: "deployment/buildspec/buildspec_prod.yaml"
        InsecureSsl: false
        Type: "CODEPIPELINE"
      Artifacts:
        EncryptionDisabled: false
        Name: "dpp-dco-cast-to-prod-auto-ses"
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache: # consider using LOCAL SOURCE CACHE like here https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html
        Type: "NO_CACHE"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        EnvironmentVariables:
          - Name: "CODEBUILD_CONFIG_AUTO_DISCOVER"
            Type: "PLAINTEXT"
            Value: "true"
        Image: public.ecr.aws/amazonlinux/amazonlinux:2023
        ImagePullCredentialsType: "SERVICE_ROLE"
        PrivilegedMode: false
        Type: "LINUX_CONTAINER"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
        S3Logs:
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

  CodePipelineDEV:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: CAST-Pipeline-dev
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Location: !Sub "codepipeline-${AWS::Region}-922520304512"
        Type: "S3"
      Stages:
        - Name: "SourceAllRepos"
          Actions:
            - Name: "SourceCastMain"
              ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Provider: "CodeStarSourceConnection"
                Version: "1"
              Configuration:
                BranchName: "DEV"
                ConnectionArn: arn:aws:codestar-connections:eu-west-1:214364534595:connection/8520c13f-d6df-4bfb-abd8-77605b5ac68d
                DetectChanges: "true"
                FullRepositoryId: "dpp-clearingoffice/CAST-main"
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: "SourceArtifactMain"
              Region: !Ref AWS::Region
              Namespace: "SourceVariablesMain"
              RunOrder: 1

            - Name: "SourceSES"
              ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Provider: "CodeStarSourceConnection"
                Version: "1"
              Configuration:
                BranchName: "DEV"
                ConnectionArn: arn:aws:codestar-connections:eu-west-1:214364534595:connection/8520c13f-d6df-4bfb-abd8-77605b5ac68d
                DetectChanges: "true"
                FullRepositoryId: "dpp-clearingoffice/CAST-email"
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: "SourceArtifactSES"
              Region: !Ref AWS::Region
              Namespace: "SourceVariablesSES"
              RunOrder: 1

        - Name: "BuildAllRepos"
          Actions:
            - Name: "BuildMain"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildMainDEV
              InputArtifacts:
                - Name: "SourceArtifactMain"
              Region: !Ref AWS::Region
              RunOrder: 1

            - Name: "BuildSES"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildSesDEV
              InputArtifacts:
                - Name: "SourceArtifactSES"
              Region: !Ref AWS::Region
              RunOrder: 1

  CodePipelinePROD:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: CAST-Pipeline-prod
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Location: !Sub "codepipeline-${AWS::Region}-922520304512"
        Type: "S3"
      Stages:
        - Name: "Source"

          Actions:
            - Name: "Source"
              ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Provider: "CodeStarSourceConnection"
                Version: "1"
              Configuration:
                BranchName: "PROD" # later test for different branches
                ConnectionArn: arn:aws:codestar-connections:eu-west-1:214364534595:connection/8520c13f-d6df-4bfb-abd8-77605b5ac68d
                DetectChanges: "true"
                FullRepositoryId: "dpp-clearingoffice/CAST-main"
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: "SourceArtifact"
              Region: !Ref AWS::Region
              Namespace: "SourceVariables"
              RunOrder: 1

            - Name: "SourceSES"
              ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Provider: "CodeStarSourceConnection"
                Version: "1"
              Configuration:
                BranchName: "PROD"
                ConnectionArn: arn:aws:codestar-connections:eu-west-1:214364534595:connection/8520c13f-d6df-4bfb-abd8-77605b5ac68d
                DetectChanges: "true"
                FullRepositoryId: "dpp-clearingoffice/CAST-email"
                OutputArtifactFormat: "CODE_ZIP"
              OutputArtifacts:
                - Name: "SourceArtifactSES"
              Region: !Ref AWS::Region
              Namespace: "SourceVariablesSES"
              RunOrder: 1
        - Name: "BuildProd"

          Actions:
            - Name: "BuildProd"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildMainPROD
              InputArtifacts:
                - Name: "SourceArtifact"
              Region: !Ref AWS::Region
              RunOrder: 1

            - Name: "BuildSES"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              Configuration:
                ProjectName: !Ref CodeBuildSesPROD
              InputArtifacts:
                - Name: "SourceArtifactSES"
              Region: !Ref AWS::Region
              RunOrder: 1
