version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam build --template template.yaml
      - echo "installing own CAST package"
      - echo "building environemnt"
      - pip install bandit
      - bandit test_code.py
  post_build:
    commands:
      - sam deploy --config-env default --no-fail-on-empty-changeset
