version: 0.2
env:
 shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
      commands:
        - source cfn-lint.sh
        - pip install bandit
        - bandit test_code.py
      # on-failure: ABORT
  build:
    commands:
      # - sam build --template template.yaml
      - echo "installing own CAST package"
      - echo "building environemnt"

  post_build:
    commands:
      - ROLE_ARN=arn:aws:iam::471685057907:role/cdk-cast-file-publishing-role-471685057907-eu-west-1
      - OUTPUT_PROFILE=DEV

      - echo "Assuming role $ROLE_ARN"
      - sts=$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name "$OUTPUT_PROFILE" --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text)
      - echo "Converting sts to array"
      - sts=($sts)
      - echo "AWS_ACCESS_KEY_ID is ${sts[0]}"
      - aws configure set aws_access_key_id ${sts[0]} --profile $OUTPUT_PROFILE
      - aws configure set aws_secret_access_key ${sts[1]} --profile $OUTPUT_PROFILE
      - aws configure set aws_session_token ${sts[2]} --profile $OUTPUT_PROFILE
      - echo "credentials stored in the profile named $OUTPUT_PROFILE"
      - sam deploy --config-env dev --profile DEV --no-fail-on-empty-changeset
