version: 0.2
env:
 shell: bash
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
      commands:
        # - source cfn-lint.sh
        # - source code-scan.sh
        - echo skipping pre-build for dev
      # on-failure: ABORT
  build:
    commands:
      - sam build --template template.yaml
  post_build:
    commands:
      - source variables.sh
      - echo ${DEPLOYER_ROLE_ARN_DEV}
      - source assume_deploy.sh
      - sam deploy --config-env resources-dev --profile DEV --no-fail-on-empty-changeset
