version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam build --template template.yaml
      - echo "installing own CAST package"
      - echo "building environemnt"
  post_build:
    commands:
      - aws sts assume-role --role-arn arn:aws:iam::471685057907:role/cdk-cast-file-publishing-role-471685057907-eu-west-1 --role-session-name testx > cred.json       
      - s=$(jq .Credentials.AccessKeyId cred.json)       
      - y=$(jq .Credentials.SecretAccessKey cred.json)       
      - z=$(jq .Credentials.SessionToken cred.json)       
      - export AWS_ACCESS_KEY_ID=$s       
      - export AWS_SECRET_ACCESS_KEY=$y       
      - export AWS_SESSION_TOKEN=$z       
      - sam deploy --config-env dev --no-fail-on-empty-changeset
