version=0.1

[default.global.parameters]
[default.build.parameters]
[default.deploy.parameters]
stack_name = 'CAST-test-repo'
region = 'eu-west-1'
capabilities = 'CAPABILITY_NAMED_IAM'
tags=" GITC- GITC-Risk Class=\"3\" GITC- Data Classification=\"internal\" GITC- Data Classification=\"true\" GITC-ApplicationID=\"82299\" backup=\"true\" "
parameter_overrides=[
    'Env=dev'
]


[dev.deploy.parameters]
stack_name = 'CAST-test-repo'
s3_bucket = "cdk-cast-assets-471685057907-eu-west-1"
region = 'eu-west-1'
capabilities = 'CAPABILITY_NAMED_IAM'
tags=" GITC- GITC-Risk Class=\"3\" GITC- Data Classification=\"internal\" GITC- Data Classification=\"true\" GITC-ApplicationID=\"82299\" backup=\"true\" "
parameter_overrides=[
    'Env=dev'
]