version = 0.1

[default.global.parameters]
[default.build.parameters]
[default.deploy.parameters]


#########################################################
# PIPELINE
#########################################################
[pipe.deploy.parameters]
stack_name = 'pipelines'
region = 'eu-west-1'
capabilities = 'CAPABILITY_NAMED_IAM'
parameter_overrides = ['Env=dev', 'StackId=-test']


#########################################################
# DEV
#########################################################

[bootstrap-dev.deploy.parameters]
stack_name = 'dev-pipe-bootstrap'
region = 'eu-west-1'
capabilities = 'CAPABILITY_NAMED_IAM'

#########################################################

[resources-dev.deploy.parameters]
stack_name = 'target-resources'
s3_bucket = "artifact-bucket-dev"
region = 'eu-west-1'
capabilities = 'CAPABILITY_NAMED_IAM'
parameter_overrides = [
    'Env=dev',
    'StackId=-test',
]


#########################################################
# PROD
#########################################################

[bootstrap-prod.deploy.parameters]
stack_name = 'prod-pipe-bootstrap'
region = 'eu-west-1'
capabilities = 'CAPABILITY_NAMED_IAM'

#########################################################

[resources-prod.deploy.parameters]
stack_name = 'dev-resources'
s3_bucket = "artifact-bucket-prod"
region = 'eu-west-1'
capabilities = 'CAPABILITY_NAMED_IAM'
tags = " version=\"0.1\" "
parameter_overrides = [
    'Env=prod']
